### ISSUE TITLE
Migration drops Postgis Sequences 

### ISSUE THREAD

**Issue by ThomasBerends** [longitude-one/doctrine-spatial#108]
Hi. I'm probably doing something wrong myself, but here's my steps:

For a database with postgis, I'm using the official docker image `postgis/postgis:16-master`.

I've installed `longitude-one/doctrine-spatial` (version 5.0.2) and I've added the following to my config:

```
doctrine:
    dbal:
        types:
            geography: LongitudeOne\Spatial\DBAL\Types\GeographyType
            point: LongitudeOne\Spatial\DBAL\Types\Geography\PointType
```

This works as expected.

When I run `php bin/console make:migration`, it creates a migration succesfully, however, it contains this:

```
        $this->addSql('DROP SEQUENCE topology.topology_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE tiger.county_gid_seq CASCADE');
        $this->addSql('DROP SEQUENCE tiger.state_gid_seq CASCADE');
        $this->addSql('DROP SEQUENCE tiger.place_gid_seq CASCADE');
        $this->addSql('DROP SEQUENCE tiger.cousub_gid_seq CASCADE');
        $this->addSql('DROP SEQUENCE tiger.edges_gid_seq CASCADE');
        $this->addSql('DROP SEQUENCE tiger.addrfeat_gid_seq CASCADE');
        $this->addSql('DROP SEQUENCE tiger.faces_gid_seq CASCADE');
        $this->addSql('DROP SEQUENCE tiger.featnames_gid_seq CASCADE');
        $this->addSql('DROP SEQUENCE tiger.addr_gid_seq CASCADE');
        $this->addSql('DROP SEQUENCE tiger.zcta5_gid_seq CASCADE');
        $this->addSql('DROP SEQUENCE tiger.tract_gid_seq CASCADE');
        $this->addSql('DROP SEQUENCE tiger.tabblock_gid_seq CASCADE');
        $this->addSql('DROP SEQUENCE tiger.bg_gid_seq CASCADE');
        $this->addSql('DROP SEQUENCE tiger.pagc_gaz_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE tiger.pagc_lex_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE tiger.pagc_rules_id_seq CASCADE');
```

The same issue is described in [this blog here](https://nerdpress.org/2022/10/31/doctrine-migrations-and-postgis/), and while the problem seems correct, I feel the solution provided there is not the correct one since I expect this package to have a solution to this.

Is there something I'm missing?

**Comment by ThomasBerends** [comment]
It worked like this:
```
doctrine:
    dbal:
        schema_filter: '~^(?!tiger)~'
```

Would it be an idea to add this to the documentation? I can make a PR, but not sure if it's desired or not.

**Comment by Alexandre-T** [comment]
Thank you for your feedback !

Even if it's more an issue linked to doctrine-migration, IMHO it could be great to add your answer to the document. Feel free to make a PR ! Thanks again !
