### ISSUE TITLE
Allow to use latest changes in wkb-parser

### ISSUE THREAD

**Issue by Bat1stuff** [longitude-one/doctrine-spatial#34]
There was a deprecation notice fix in [wkb-parser](https://github.com/creof/wkb-parser) so could you please allow to use dev-master branch instead of ~2.3.

**Comment by Alexandre-T** [comment]
Closed because of update on wkb-parser
https://github.com/creof/wkb-parser/commit/8b671b7be0700ff04962bdb0681bb2b1626367d0
