### ISSUE TITLE
Replacement of `creof/wkt-parser` to not depend on `doctrine/lexer:~1.0`

### ISSUE THREAD

**Issue by misaert** [longitude-one/doctrine-spatial#36]
Hi,

Have you planned to replace `creof/wkt-parser`? Because it creates a dependency on `doctrine/lexer:~1.0` and this package has now 2 new major versions. Several packages require at least `doctrine/lexer:^2` like `doctrine/annotations:2.0.1` and `friendsofphp/php-cs-fixer:v3.14.4` require `doctrine/annotations:^2`.

I created an [issue](https://github.com/creof/wkt-parser/issues/13) on this package too.
Thanks,

Mickaël

**Comment by Alexandre-T** [comment]
Hi,

Thank you for your interest. I would like to improve this library, but days are too short ^^. First of all, I need to look how many times `lexer` is called in `wkt-parser`. Then I need to evaluate how upgrade will be easy. Of course, I will appreciate if anyone can push a request, but contributors are rare, contributions even rarer. If someone can start and evaluate the impact on code, it would help me to estimate the time needed for this improvement

**Comment by axi** [comment]
I created a pull request on [creof/wkt-parser](https://github.com/creof/wkt-parser/pull/14), let's see what happen

**Comment by ellisgl** [comment]
@axi I don't think you are going to get anywhere - since it doesn't look like creof has updated these packeages in like 6-7 years, with PRs outstanding also for years.

I would create a hard fork of the library like longitiude-one did with doctrine-spatial.

**Comment by axi** [comment]
@Alexandre-T would that be ok for longitude-one to hard-fork creof/wkt-parser same way it forked doctrine-spatial ?

**Comment by Alexandre-T** [comment]
Done : https://github.com/longitude-one/wkt-parser

**Comment by ellisgl** [comment]
Next we need to updated it, rename it and, get it up on Packagist and then link to it!!

**Comment by Alexandre-T** [comment]
Composer is updated, the package is renamed and declared on packagist.
I try to work on it on Monday. IMO we can focus on compatibility with PHP 8.1+ only. Do you agree?

**Comment by ellisgl** [comment]
Yeah, getting updated to the minimum supported version of PHP makes sense.

**Comment by axi** [comment]
A start here #37

**Comment by Alexandre-T** [comment]
I still have to tag a new major version. I try to check tags this week-end.

**Comment by misaert** [comment]
Hi @Alexandre-T,

Have you planned the release of the new version?

Thank you,

Mickaël

**Comment by Alexandre-T** [comment]
Hi @misaert 

The [4.0.0-rc1](https://github.com/longitude-one/doctrine-spatial/releases/tag/4.0.0-rc1) is released. 

If there are no new issues linked to this RC, we will be able to release the 4.0.0.

**Comment by Alexandre-T** [comment]
No issues for two weeks, [4.0.0 released](https://github.com/longitude-one/doctrine-spatial/releases/tag/4.0.0). 🥇
