### ISSUE TITLE
User Deprecated: AbstractMySQLPlatform::getName()

### ISSUE THREAD

**Issue by alveri** [longitude-one/doctrine-spatial#40]
User Deprecated: AbstractMySQLPlatform::getName() is deprecated. Identify platforms by their class. (AbstractMySQLPlatform.php:1212 called by AbstractSpatialType.php:231

https://github.com/doctrine/dbal/issues/4749

**Comment by Alexandre-T** [comment]
I am currently forking and updating libraries (`geo-parser` and `wkt-parser`) required to migrate to `doctrine/lexer:3`. The goal is to make `doctrine-spatial` compatible with `doctrine/orm:3`.

**Comment by Alexandre-T** [comment]
`geo-parser` and `wkt-parser` have been upgraded. Two release candidates have been published (3.0.0.RC).
You can follow the progress on issue #43 (but I'm still working on my spare time, so I cannot tell you when this will be done).

**Comment by geoffroyp** [comment]
Thank you very much for your time and effort!

**Comment by Alexandre-T** [comment]
The `AbstractMySQLPlatform::getName` is no longer used. 

I guess you can use the [last commit](https://github.com/longitude-one/doctrine-spatial/commit/f54f57a0cbce9a9639088a1e201ea575c57a0a99) to test it.

`composer require longitude-one/doctrine-spatial:dev-doctrine3-feature --prefer-stable`

The IDE detected other deprecated calls, such as Lexer constants. I will fix these before merging the changes into dev branch.
