### ISSUE TITLE
BC breaks upgrding doctrine/dbal from 3.6.x to 3.7.x. Undefined array key "type" ErrorException

### ISSUE THREAD

**Issue by julienbornstein** [longitude-one/doctrine-spatial#42]
After updating doctrine/dbal from 3.6.x to 3.7.x I get some errors 

`Spatial/DBAL/Platform/MySql.php:65`

```
[ErrorException]                     
Warning: Undefined array key "type"
```

the code : 

```php
 /**
     * Gets the SQL declaration snippet for a field of this type.
     *
     * @param array $fieldDeclaration array SHALL contains 'type' as key
     *
     * @return string
     */
    public function getSqlDeclaration(array $fieldDeclaration)
    {
        if (GeographyInterface::GEOGRAPHY === $fieldDeclaration['type']->getSQLType()) {
            return 'GEOMETRY';
        }

        return mb_strtoupper($fieldDeclaration['type']->getSQLType());
    }
```

As the phpdoc says _$fieldDeclaration array **SHALL contains** 'type' as key_. But after migrating to dbal 3.7, `$fieldDeclaration` doesn't contain `type` key

`$fieldDeclaration` dump from 3.6
```php
[
  "name" => "latlng"
  "type" => LongitudeOne\Spatial\DBAL\Types\GeographyType^ {#630}
  "default" => null
  "notnull" => true
  "length" => 0
  "precision" => 10
  "scale" => 0
  "fixed" => false
  "unsigned" => false
  "autoincrement" => false
  "comment" => "(DC2Type:geography)"
  "version" => false
]
```

`$fieldDeclaration` dump from 3.7
```php
[
  "length" => 0
  "unsigned" => false
  "fixed" => false
  "default" => null
  "notnull" => true
  "scale" => null
  "precision" => null
  "autoincrement" => false
  "comment" => null
]
```

**Comment by Alexandre-T** [comment]
I'll try to fix this bug asap. IMO, I need to use `$type->requiresSQLCommentHint($platform)` instead of `fieldDeclaration['type']`

**Comment by Alexandre-T** [comment]
@julienbornstein , I found a (non-elegant) way to no longer use `type`, but are you sure about your tests? I'm using `doctrine/dbal:3.8` and it looks like type is still used and not deprecated. It looks like `type` is still being submitted on [this line](https://github.com/doctrine/dbal/blob/edbf3076e2b23a2c696de01bd9f39faa643c05f4/src/Platforms/AbstractPlatform.php#L3069).

**Comment by Alexandre-T** [comment]
Fixed in doctrine-feature branch
