### ISSUE TITLE
Introduction of Point3D and Point4D: Geometric 2D points shall only accepts three arguments: $x, $y and optional $srid

### ISSUE THREAD

**Issue by Alexandre-T** [longitude-one/doctrine-spatial#81]
In the next major version, I would like to introduce three and four dimensional points. Geometric, and geographic ones. 

But the constructor of abstract point class is already over-complex. PHP-Mess-Detector score at 54... Toooo much to be safe. This tolerance in the constructor is the source of most bugs.

IMO, we should break it and only allow standard constructors accepting the coordinates and the optional SRID.

- [x] So, the next minor versions of doctrine-spatial will throw deprecation when developers won't use standard constructor,
- [x] The next major version won't accept constructor with array or WKT coordinates (coordinates separated with a space, like `3 2` in `POINT(3 2)` )

Then, I'll be able to introduce 3D and 4D geometries.

**Comment by jrmgx** [comment]
I'll be very happy when this lands on the dev branch, I'm already using 3d-point-feature branch but it's not fully ready (LineString does not reflect Point3D from what I see, etc). Thank you for your project it's much appreciated.

**Comment by jrmgx** [comment]
I guess it comes from 
```php
    /**
     * Convert a point to a string value.
     *
     * @param (float|int)[] $point point already converted into an array of TWO coordinates
     */
    private function toStringPoint(array $point): string
    {
        return vsprintf('%s %s', $point);
    }
```
that does not handle point with more than TWO coordinates, but I feel that this simple change will cascade to other changes, etc.

**Comment by Alexandre-T** [comment]
> I'll be very happy when this lands on the dev branch, I'm already using 3d-point-feature branch but it's not fully ready (LineString does not reflect Point3D from what I see, etc). Thank you for your project it's much appreciated.

Yes, it's not ready yet, and it's not a nightly build. The code is unstable and could break at any time. I'm currently working on MariaDB integration and a new internal MySQL process to store SRIDs. Please be cautious, as this is an alpha branch, and functionalities may change without notice.



> I guess it comes from
> 
> ```
>     /**
>      * Convert a point to a string value.
>      *
>      * @param (float|int)[] $point point already converted into an array of TWO coordinates
>      */
>     private function toStringPoint(array $point): string
>     {
>         return vsprintf('%s %s', $point);
>     }
> ```
> 
> that does not handle point with more than TWO coordinates, but I feel that this simple change will cascade to other changes, etc.

Exactly! And I'm working to a new way to export the internal objects. The default __toString() will disappear and be replaced by converters/adapters. There are a lot of tasks and I cannot tell you when the release will be publish. (I'm only working on it on my free time.)

**Comment by jrmgx** [comment]
Don't worry, take the time you need, it was just my way of saying thanks for the job.
I'm exploring your lib, but I won't use it for production project, just playing a bit!
Good luck and keep up the good work :)
